#ifndef PRINTERLIB_GLOBAL_H
#define PRINTERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PRINTERLIB_LIBRARY)
#  define PRINTERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PRINTERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif
#define DLLEXPORT extern "C" PRINTERLIBSHARED_EXPORT
#endif // PRINTERLIB_GLOBAL_H
