#ifndef NOTEPRINTER_SP320_GLOBAL_H
#define NOTEPRINTER_SP320_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NOTEPRINTER_SP320_LIBRARY)
#  define NOTEPRINTER_SP320SHARED_EXPORT Q_DECL_EXPORT
#else
#  define NOTEPRINTER_SP320SHARED_EXPORT Q_DECL_IMPORT
#endif
#define DLLEXPORT extern "C" NOTEPRINTER_SP320SHARED_EXPORT
#endif // NOTEPRINTER_SP320_GLOBAL_H
