#ifndef CARDFILEMGR_GLOBAL_H
#define CARDFILEMGR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CARDFILEMGR_LIBRARY)
#  define CARDFILEMGRSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CARDFILEMGRSHARED_EXPORT Q_DECL_IMPORT
#endif
#define API extern "C" CARDFILEMGRSHARED_EXPORT
#endif // CARDFILEMGR_GLOBAL_H
