#ifndef CARDMGRLIB_GLOBAL_H
#define CARDMGRLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CARDMGRLIB_LIBRARY)
#  define CARDMGRLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CARDMGRLIBSHARED_EXPORT Q_DECL_IMPORT
#endif
#define API extern "C" CARDMGRLIBSHARED_EXPORT
#endif // CARDMGRLIB_GLOBAL_H
