#ifndef NOTEPRINTER_GLOBAL_H
#define NOTEPRINTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NOTEPRINTER_LIBRARY)
#  define NOTEPRINTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NOTEPRINTERSHARED_EXPORT Q_DECL_IMPORT
#endif
#define DLLEXPORT extern "C" NOTEPRINTERSHARED_EXPORT

#endif // NOTEPRINTER_GLOBAL_H
